### ISSUE TITLE
Typo!

### ISSUE THREAD

**Issue by LuizBreak** [Robert1802/CSharp-CheatSheet#1]
Hi Robert,

How r u?

In your Readme file there is a minor typo.

it reads: **Hare** you will have

it should read **Here** you will have.

My apologies if I misunderstood it.

Cheers,
Luiz

**Comment by Robert1802** [comment]
> Hi Robert,
> 
> How r u?
> 
> In your Readme file there is a minor typo.
> 
> it reads: **Hare** you will have
> 
> it should read **Here** you will have.
> 
> My apologies if I misunderstood it.
> 
> Cheers, Luiz

Thanks for noticing that, fixed it here. Gonna update it ASAP.
